package com.rahafcs.co.rightway.utility

object Constant {
    const val USERID = "userId"
    const val FIRST_NAME = "firstName"
    const val SUPERSCRIPTION = "SubscriptionStatus"
    const val GENDER = "gender"
    const val HEIGHT = "height"
    const val WEIGHT = "weight"
    const val AGE = "age"
    const val SIGN_IN = "signIn"
    const val ACTIVITY_LEVEL = "activityLevel"
    const val SIGN_UP = "signUp"
    const val LAST_NAME = "lastName"
    const val COACH_EMAIL = "coachEmail"
    const val COACH_PHONE = "coachPhone"
    const val COACH_EXPERIENCE = "coachExperience"
    const val COACH_PRICE_RANGE = "priceRange"
    const val ERROR_MESSAGE = "errorMessage"
    const val RAPID_API_KEY = "ccb06bc4c0mshb7a29f7814116c6p14a25ajsn3cfb231e6ceb"
    const val PRE_MESSAGE = "preMessage"
    const val PRE_SUBJECT = "preSubject"
    const val PRE_EMAIL = "preEmail"
    const val BARBELL = "barbell"
    const val DUMBBELL = "dumbbell"
    const val CABLE = "cable"
    const val KETTLE_BELL = "kettlebell"
    const val RESISTANCE_BAND = "resistance band"
    const val BODY_WEIGHT = "body weight"
    const val ALL_EQUIPMENT = "allEquipment"
}
